server:
  port: 8081

spring:
  application:
    name: mll
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ping?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null

  data:
    redis:
      port: 6379
      host: localhost
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      password: null
      connectionPoolSize: 64
      connectionMinimumIdleSize: 24
mybatis-plus:
  type-aliases-package: com.mll.entity

logging:
  level:
    com.mll: INFO
  pattern:
    dateformat: mm:ss.SSS

worker:
  id: 1
datacenter:
  id: 1
